python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks3.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks4.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks5.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks6.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks7.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks8.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks9.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks10.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks11.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks12.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks13.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks14.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks15.yaml
python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks50.yaml
